### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by mathvav**
I hereby license all of my submitted content under the MIT license, as included in this repository.

### CODE REVIEW

**Comment by mathvav** [comment]
Thanks @ShearOfDoom 

Make sure that everyone approves this modified MIT license before pulling for legal reasons (remember I'm not a lawyer :P)

**Comment by nic-hartley** [comment]
Looks good to me, though strictly speaking I don't think the software was _developed by_ The Cactus Project, so the working could be improved.

**Comment by mathvav** [comment]
Errr.... what do you want?

It might be too late with different versions of licenses

**Comment by nic-hartley** [comment]
Eh, just being pedantic. It looks fine.

**Comment by mathvav** [comment]
TBH we all know it's going deep in some about page that takes 15651651564 steps to get to :smirk:

**Comment by nic-hartley** [comment]
Fair point, fair point. Either way, I'm good with it.

**Pull request merged**
